exclude: ^docs/

repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
    -   id: isort
        exclude: ^notebooks/

-   repo: https://github.com/psf/black
    rev: 21.4b0
    hooks:
    -   id: black
        args:
            - "--line-length=88"
        exclude: ^notebooks/

-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.1
    hooks:
    -   id: flake8
        exclude: ^notebooks/
