repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
    -   id: isort
        exclude: ^notebooks/

-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
        args:
            - "--line-length=88"
        exclude: ^notebooks/

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        exclude: ^notebooks/
