# misc
notifications:
  email: false
sudo: false

# python settings
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

# install packages
install:
  - pip install -r requirements_test.txt
  - pip install -e .

# run test
script:
  - python -m pytest
