name: prospect-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8
  - geopandas
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - black
  - isort
  - flake8
  - pre-commit
  - pytest
  - pytest-cov
  - mypy
  - rope
  - jupytext
  - seaborn
  - sphinx
  - twine
  - pip
  - pip:
    - jupyter-book
    - ghp-import
