name: prospect
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.7
  - geopandas
  - descartes
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - scipy
  - sqlalchemy
  - black
  - isort
  - flake8
  - pre-commit
  - pytest
  - pytest-cov
  - mypy
  - rope
  - jupytext
  - voila-gridstack
  - pip:
    - jupyter-book
    - cookiecutter
