name: surveysim
channel_priority: strict
channels:
  - conda-forge
  - conda
  - defaults
dependencies:
  - python=3.6
  - jupyter
  - jupyterlab
  - nodejs
  - pandas
  - numpy
  - geopandas
  - flake8
  - autopep8
  - mypy
  - pytest
