name: prospect
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.6.7
  - appnope==0.1.0
  - atomicwrites==1.3.0
  - attrs==19.1.0
  - autopep8==1.4.3
  - backcall==0.1.0
  - bleach==3.1.0
  - certifi==2018.11.29
  - Click==7.0
  - click-plugins==1.0.4
  - cligj==0.5.0
  - cycler==0.10.0
  - decorator==4.3.2
  - defusedxml==0.5.0
  - descartes==1.1.0
  - docformatter==1.1
  - entrypoints==0.3
  - Fiona==1.8.4
  - flake8==3.7.7
  - GDAL==2.4.0
  - geopandas==0.4.1
  - ipykernel==5.1.0
  - ipython==7.3.0
  - ipython-genutils==0.2.0
  - ipywidgets==7.4.2
  - jedi==0.13.3
  - Jinja2==2.10
  - jsonschema==3.0.1
  - jupyter==1.0.0
  - jupyter-client==5.2.4
  - jupyter-console==6.0.0
  - jupyter-core==4.4.0
  - jupyterlab==0.35.4
  - jupyterlab-server==0.2.0
  - kiwisolver==1.0.1
  - mapclassify==2.0.1
  - MarkupSafe==1.1.1
  - matplotlib==3.0.3
  - mccabe==0.6.1
  - mistune==0.8.4
  - more-itertools==4.3.0
  - munch==2.3.2
  - mypy==0.670
  - mypy-extensions==0.4.1
  - nbconvert==5.4.1
  - nbformat==4.4.0
  - notebook==5.7.5
  - numpy==1.16.2
  - pandas==0.24.1
  - pandocfilters==1.4.2
  - parso==0.3.4
  - pexpect==4.6.0
  - pickleshare==0.7.5
  - pluggy==0.9.0
  - prometheus-client==0.6.0
  - prompt-toolkit==2.0.9
  - psutil==5.4.8
  - ptyprocess==0.6.0
  - py==1.8.0
  - pycodestyle==2.5.0
  - pyflakes==2.1.1
  - Pygments==2.3.1
  - pyparsing==2.3.1
  - pyproj==1.9.6
  - pyrsistent==0.14.11
  - pytest==4.3.0
  - python-dateutil==2.8.0
  - pytz==2018.9
  - pyzmq==18.0.1
  - qtconsole==4.4.3
  - rope==0.10.7
  - Rtree==0.8.3
  - scipy==1.2.1
  - Send2Trash==1.5.0
  - Shapely==1.6.4.post2
  - six==1.12.0
  - SQLAlchemy==1.3.0
  - terminado==0.8.1
  - testpath==0.4.2
  - tornado==6.0.1
  - traitlets==4.3.2
  - typed-ast==1.3.1
  - typing==3.6.4
  - typing-extensions==3.7.2
  - untokenize==0.1.1
  - wcwidth==0.1.7
  - webencodings==0.5.1
  - widgetsnbextension==3.4.2
