name: prospect
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.7
  - black
  - flake8
  - geopandas
  - descartes
  - jupyter
  - jupyterlab
  - matplotlib
  - mypy
  - numpy
  - pandas
  - pytest
  - rope
  - scipy
  - sqlalchemy
  - jupytext
