name: deploy_docs

on:
  # Trigger the workflow on push to master branch
  push:
    branches:
      - master

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-and-deploy-book:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up conda env with dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channels: conda-forge, defaults
        channel-priority: true
        activate-environment: prospect-docs
        environment-file: docs_environment.yml
        auto-activate-base: false
    - name: Install prospect in dev mode
      shell: bash -l {0}
      run: |
        python3 -m pip install -e .

    # Build the book
    - name: Build the book
      shell: bash -l {0}
      run: |
        jupyter-book build docs/prospect-guide

    # Deploy the book's HTML to gh-pages branch
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/prospect-guide/_build/html
