name: Run tests

on: push


jobs:
  tests:
    name: Tests (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up conda env with dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channels: conda-forge, defaults
        channel-priority: true
        activate-environment: prospect-test
        environment-file: test_environment.yml
        auto-activate-base: false
    - name: Install prospect in dev mode
      shell: bash -l {0}
      run: |
        python3 -m pip install -e .
    - name: Run tests with coverage
      shell: bash -l {0}
      run: |
        pytest --cov="prospect" --cov-report=xml
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./coverage.xml
        fail_ci_if_error: true
